da

diff --git a/.github/workflows/backend-ci.yaml b/.github/workflows/backend-ci.yaml
--- a/.github/workflows/backend-ci.yaml
+++ b/.github/workflows/backend-ci.yaml
@@ -1,13 +1,12 @@
 name: Backend Continuous Integration
 
 on:
-  # This allows running on-demand
+  # Trigger manually or on pull requests
   workflow_dispatch:
   pull_request:
     branches:
       - main
     paths:
-      # This will only run on changes to the backend code
       - "backend/**"
 
 env:
@@ -24,6 +23,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Debug file structure
+        run: ls -R ./backend || echo "Backend directory not found"
+
       - name: Cache pipenv dependencies
         uses: actions/cache@v3
         with:
@@ -35,22 +37,19 @@ jobs:
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{env.PYTHON_VERSION}}
+          python-version: ${{ env.PYTHON_VERSION }}
 
       - name: Install pipenv
-        run: |
-          pip install pipenv
+        run: pip install pipenv
 
       - name: Install dependencies
-        run: |
-          pipenv install && pip install flake8
+        run: pipenv install --dev
 
       - name: Run lint
-        run: |
-          pipenv run lint
+        run: pipenv run flake8 .
 
   test:
-    name: Backend run test
+    name: Backend run tests
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -59,25 +58,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Debug file structure
+        run: ls -R ./backend || echo "Backend directory not found"
+
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{env.PYTHON_VERSION}}
+          python-version: ${{ env.PYTHON_VERSION }}
 
       - name: Install pipenv
-        run: |
-          pip install pipenv
+        run: pip install pipenv
 
       - name: Install dependencies
-        run: |
-          pipenv install
+        run: pipenv install --dev
 
       - name: Run tests
-        run: |
-          pipenv run test
-          
+        run: pipenv run pytest
+
   build:
-    name: Build & push image
+    name: Build & push Docker image
     runs-on: ubuntu-latest
     needs: [lint, test]
     defaults:
@@ -87,18 +86,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Debug file structure
+        run: ls -R ./backend || echo "Backend directory not found"
+
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{env.PYTHON_VERSION}}
+          python-version: ${{ env.PYTHON_VERSION }}
 
       - name: Install pipenv
-        run: |
-          pip install pipenv && pip install flake8
+        run: pip install pipenv
 
       - name: Install dependencies
-        run: |
-          pipenv install
+        run: pipenv install --dev
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -110,17 +110,15 @@ jobs:
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
-        with:
-          mask-password: "true"
 
-      - name: Build, Tag, and Push docker image
+      - name: Build, tag, and push Docker image
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           REPOSITORY: backend
           IMAGE_TAG: latest
         run: |
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
-          docker images
+          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
       - name: Cache Docker image
         uses: actions/cache@v3
